var py_arguments = {};
var attribs_by_name = {};
var byte_arrays = {};
var callable_test = {};
var classes = {};
var complex_numbers = {};
var conditional_expressions = {};
var control_structures = {};
var data_structures = {};
var decorators = {};
var dict_comprehensions = {};
var dictionaries = {};
var div_pulls = {};
var docstrings = {};
var extended_slices = {};
var fstrings = {};
var general_functions = {};
var globals_function = {};
var indices_and_slices = {};
var lambda_functions = {};
var list_comprehensions = {};
var local_classes = {};
var metaclasses = {};
var method_and_class_decorators = {};
var module_builtin = {};
var module_cmath = {};
var module_math = {};
var modules = {};
var nonlocals = {};
var operator_overloading = {};
var org = {};
var properties = {};
var reprtest = {};
var set_comprehensions = {};
var simple_and_augmented_assignment = {};
var truthyness = {};
var tuple_assignment = {};
import {__envir__, __nest__, __init__, __get__, __getcm__, __getsm__, py_metatype, object, __class__, __pragma__, __call__, __kwargtrans__, __globals__, __super__, property, __setProperty__, __merge__, dir, setattr, getattr, hasattr, delattr, __in__, __specialattrib__, len, __i__, __k__, __t__, float, int, bool, py_typeof, issubclass, isinstance, callable, repr, chr, ord, max, min, abs, round, __jsUsePyNext__, __pyUseJsNext__, py_iter, py_next, __PyIterator__, __JsIterator__, py_reversed, zip, range, any, all, sum, enumerate, copy, deepcopy, list, tuple, set, bytearray, bytes, str, dict, __jsmod__, __mod__, __pow__, __neg__, __matmul__, __mul__, __truediv__, __floordiv__, __add__, __sub__, __lshift__, __rshift__, __or__, __xor__, __and__, __eq__, __ne__, __lt__, __le__, __gt__, __ge__, __imatmul__, __ipow__, __ijsmod__, __imod__, __imul__, __idiv__, __iadd__, __isub__, __ilshift__, __irshift__, __ior__, __ixor__, __iand__, __getitem__, __setitem__, __getslice__, __setslice__, Exception, IterableError, StopIteration, ValueError, KeyError, AssertionError, NotImplementedError, IndexError, AttributeError, py_TypeError, Warning, UserWarning, DeprecationWarning, RuntimeWarning, __sort__, sorted, map, filter, complex, __conj__, __Terminal__, __terminal__, print} from './org.transcrypt.__runtime__.mod.js';
var __name__ = '__main__';
import * as __module_org_transcrypt_autotester__ from './org.transcrypt.autotester.mod.js';
__nest__ (org, 'transcrypt.autotester', __module_org_transcrypt_autotester__);
import * as __module_py_arguments__ from './arguments.mod.js';
__nest__ (py_arguments, '', __module_py_arguments__);
import * as __module_attribs_by_name__ from './attribs_by_name.mod.js';
__nest__ (attribs_by_name, '', __module_attribs_by_name__);
import * as __module_byte_arrays__ from './byte_arrays.mod.js';
__nest__ (byte_arrays, '', __module_byte_arrays__);
import * as __module_callable_test__ from './callable_test.mod.js';
__nest__ (callable_test, '', __module_callable_test__);
import * as __module_classes__ from './classes.mod.js';
__nest__ (classes, '', __module_classes__);
import * as __module_complex_numbers__ from './complex_numbers.mod.js';
__nest__ (complex_numbers, '', __module_complex_numbers__);
import * as __module_conditional_expressions__ from './conditional_expressions.mod.js';
__nest__ (conditional_expressions, '', __module_conditional_expressions__);
import * as __module_control_structures__ from './control_structures.mod.js';
__nest__ (control_structures, '', __module_control_structures__);
import * as __module_data_structures__ from './data_structures.mod.js';
__nest__ (data_structures, '', __module_data_structures__);
import * as __module_decorators__ from './decorators.mod.js';
__nest__ (decorators, '', __module_decorators__);
import * as __module_dict_comprehensions__ from './dict_comprehensions.mod.js';
__nest__ (dict_comprehensions, '', __module_dict_comprehensions__);
import * as __module_dictionaries__ from './dictionaries.mod.js';
__nest__ (dictionaries, '', __module_dictionaries__);
import * as __module_div_pulls__ from './div_pulls.mod.js';
__nest__ (div_pulls, '', __module_div_pulls__);
import * as __module_docstrings__ from './docstrings.mod.js';
__nest__ (docstrings, '', __module_docstrings__);
import * as __module_extended_slices__ from './extended_slices.mod.js';
__nest__ (extended_slices, '', __module_extended_slices__);
import * as __module_fstrings__ from './fstrings.mod.js';
__nest__ (fstrings, '', __module_fstrings__);
import * as __module_general_functions__ from './general_functions.mod.js';
__nest__ (general_functions, '', __module_general_functions__);
import * as __module_globals_function__ from './globals_function.mod.js';
__nest__ (globals_function, '', __module_globals_function__);
import * as __module_indices_and_slices__ from './indices_and_slices.mod.js';
__nest__ (indices_and_slices, '', __module_indices_and_slices__);
import * as __module_lambda_functions__ from './lambda_functions.mod.js';
__nest__ (lambda_functions, '', __module_lambda_functions__);
import * as __module_list_comprehensions__ from './list_comprehensions.mod.js';
__nest__ (list_comprehensions, '', __module_list_comprehensions__);
import * as __module_local_classes__ from './local_classes.mod.js';
__nest__ (local_classes, '', __module_local_classes__);
import * as __module_metaclasses__ from './metaclasses.mod.js';
__nest__ (metaclasses, '', __module_metaclasses__);
import * as __module_method_and_class_decorators__ from './method_and_class_decorators.mod.js';
__nest__ (method_and_class_decorators, '', __module_method_and_class_decorators__);
import * as __module_module_builtin__ from './module_builtin.mod.js';
__nest__ (module_builtin, '', __module_module_builtin__);
import * as __module_module_cmath__ from './module_cmath.mod.js';
__nest__ (module_cmath, '', __module_module_cmath__);
import * as __module_module_math__ from './module_math.mod.js';
__nest__ (module_math, '', __module_module_math__);
import * as __module_modules__ from './modules.mod.js';
__nest__ (modules, '', __module_modules__);
import * as __module_nonlocals__ from './nonlocals.mod.js';
__nest__ (nonlocals, '', __module_nonlocals__);
import * as __module_operator_overloading__ from './operator_overloading.mod.js';
__nest__ (operator_overloading, '', __module_operator_overloading__);
import * as __module_properties__ from './properties.mod.js';
__nest__ (properties, '', __module_properties__);
import * as __module_reprtest__ from './reprtest.mod.js';
__nest__ (reprtest, '', __module_reprtest__);
import * as __module_set_comprehensions__ from './set_comprehensions.mod.js';
__nest__ (set_comprehensions, '', __module_set_comprehensions__);
import * as __module_simple_and_augmented_assignment__ from './simple_and_augmented_assignment.mod.js';
__nest__ (simple_and_augmented_assignment, '', __module_simple_and_augmented_assignment__);
import * as __module_truthyness__ from './truthyness.mod.js';
__nest__ (truthyness, '', __module_truthyness__);
import * as __module_tuple_assignment__ from './tuple_assignment.mod.js';
__nest__ (tuple_assignment, '', __module_tuple_assignment__);
export var autoTester = org.transcrypt.autotester.AutoTester ();
autoTester.run (py_arguments, 'arguments');
autoTester.run (attribs_by_name, 'attribs_by_name');
autoTester.run (byte_arrays, 'byte_arrays');
autoTester.run (callable_test, 'callable');
autoTester.run (classes, 'classes');
autoTester.run (complex_numbers, 'complex_numbers');
autoTester.run (conditional_expressions, 'conditional_expressions');
autoTester.run (control_structures, 'control_structures');
autoTester.run (data_structures, 'data_structures');
autoTester.run (decorators, 'decorators');
autoTester.run (dict_comprehensions, 'dict_comprehensions');
autoTester.run (dictionaries, 'dictionaries');
autoTester.run (div_pulls, 'div_pulls');
autoTester.run (docstrings, 'docstrings');
autoTester.run (extended_slices, 'extended_slices');
autoTester.run (fstrings, 'fstrings');
autoTester.run (general_functions, 'general_functions');
autoTester.run (globals_function, 'globals_function');
autoTester.run (indices_and_slices, 'indices_and_slices');
autoTester.run (lambda_functions, 'lambda_functions');
autoTester.run (list_comprehensions, 'list_comprehensions');
autoTester.run (local_classes, 'local_classes');
autoTester.run (metaclasses, 'metaclasses');
autoTester.run (method_and_class_decorators, 'method_and_class_decorators');
autoTester.run (module_builtin, 'module_builtin');
autoTester.run (module_cmath, 'module_cmath');
autoTester.run (module_math, 'module_math');
autoTester.run (modules, 'modules');
autoTester.run (nonlocals, 'nonlocals');
autoTester.run (operator_overloading, 'operator_overloading');
autoTester.run (properties, 'properties');
autoTester.run (reprtest, 'repr_str');
autoTester.run (set_comprehensions, 'set_comprehensions');
autoTester.run (simple_and_augmented_assignment, 'simple_and_augmented_assignment');
autoTester.run (truthyness, 'truthyness');
autoTester.run (tuple_assignment, 'tuple_assignment');
autoTester.done ();