// Transcrypt'ed from Python, 2021-05-14 15:01:24
var py_arguments = {};
var attribs_by_name = {};
var builtin_super = {};
var byte_arrays = {};
var callable_test = {};
var classes = {};
var complex_numbers = {};
var conditional_expressions = {};
var control_structures = {};
var dashed_numbers = {};
var data_classes = {};
var data_structures = {};
var decorators = {};
var dict_comprehensions = {};
var dictionaries = {};
var div_issues = {};
var div_pulls = {};
var docstrings = {};
var exceptions = {};
var executable_comments = {};
var extended_slices = {};
var fstrings = {};
var general_functions = {};
var globals_function = {};
var indices_and_slices = {};
var iterators_and_generators = {};
var lambda_functions = {};
var list_comprehensions = {};
var local_classes = {};
var metaclasses = {};
var method_and_class_decorators = {};
var module_builtin = {};
var module_cmath = {};
var module_datetime = {};
var module_itertools = {};
var module_math = {};
var module_unicodedata = {};
var modules = {};
var nonlocals = {};
var operator_overloading = {};
var org = {};
var properties = {};
var proxies = {};
var reprtest = {};
var set_comprehensions = {};
var simple_and_augmented_assignment = {};
var string_format = {};
var truthyness = {};
var tuple_assignment = {};
import {AssertionError, AttributeError, BaseException, DeprecationWarning, Exception, IndexError, IterableError, KeyError, NotImplementedError, RuntimeWarning, StopIteration, UserWarning, ValueError, Warning, __JsIterator__, __PyIterator__, __Terminal__, __add__, __and__, __call__, __class__, __conj__, __envir__, __eq__, __floordiv__, __ge__, __get__, __getcm__, __getitem__, __getslice__, __getsm__, __gt__, __i__, __iadd__, __iand__, __idiv__, __ijsmod__, __ilshift__, __imatmul__, __imod__, __imul__, __in__, __init__, __ior__, __ipow__, __irshift__, __isub__, __ixor__, __jsUsePyNext__, __jsmod__, __k__, __kwargtrans__, __le__, __lshift__, __lt__, __matmul__, __mergefields__, __mergekwargtrans__, __mod__, __mul__, __ne__, __neg__, __nest__, __or__, __pow__, __pragma__, __pyUseJsNext__, __rshift__, __setitem__, __setproperty__, __setslice__, __sort__, __specialattrib__, __sub__, __super__, __t__, __terminal__, __truediv__, __withblock__, __xor__, abs, all, any, assert, bool, bytearray, bytes, callable, chr, complex, copy, deepcopy, delattr, dict, dir, divmod, enumerate, filter, float, format, getattr, hasattr, input, int, isinstance, issubclass, len, list, map, max, min, object, ord, pow, print, property, py_TypeError, py_iter, py_metatype, py_next, py_reversed, py_typeof, range, repr, round, set, setattr, sorted, str, sum, tuple, zip} from './org.transcrypt.__runtime__.js';
import * as __module_tuple_assignment__ from './tuple_assignment.js';
__nest__ (tuple_assignment, '', __module_tuple_assignment__);
import * as __module_truthyness__ from './truthyness.js';
__nest__ (truthyness, '', __module_truthyness__);
import * as __module_string_format__ from './string_format.js';
__nest__ (string_format, '', __module_string_format__);
import * as __module_simple_and_augmented_assignment__ from './simple_and_augmented_assignment.js';
__nest__ (simple_and_augmented_assignment, '', __module_simple_and_augmented_assignment__);
import * as __module_set_comprehensions__ from './set_comprehensions.js';
__nest__ (set_comprehensions, '', __module_set_comprehensions__);
import * as __module_reprtest__ from './reprtest.js';
__nest__ (reprtest, '', __module_reprtest__);
import * as __module_proxies__ from './proxies.js';
__nest__ (proxies, '', __module_proxies__);
import * as __module_properties__ from './properties.js';
__nest__ (properties, '', __module_properties__);
import * as __module_operator_overloading__ from './operator_overloading.js';
__nest__ (operator_overloading, '', __module_operator_overloading__);
import * as __module_nonlocals__ from './nonlocals.js';
__nest__ (nonlocals, '', __module_nonlocals__);
import * as __module_modules__ from './modules.js';
__nest__ (modules, '', __module_modules__);
import * as __module_module_unicodedata__ from './module_unicodedata.js';
__nest__ (module_unicodedata, '', __module_module_unicodedata__);
import * as __module_module_math__ from './module_math.js';
__nest__ (module_math, '', __module_module_math__);
import * as __module_module_itertools__ from './module_itertools.js';
__nest__ (module_itertools, '', __module_module_itertools__);
import * as __module_module_datetime__ from './module_datetime.js';
__nest__ (module_datetime, '', __module_module_datetime__);
import * as __module_module_cmath__ from './module_cmath.js';
__nest__ (module_cmath, '', __module_module_cmath__);
import * as __module_module_builtin__ from './module_builtin.js';
__nest__ (module_builtin, '', __module_module_builtin__);
import * as __module_method_and_class_decorators__ from './method_and_class_decorators.js';
__nest__ (method_and_class_decorators, '', __module_method_and_class_decorators__);
import * as __module_metaclasses__ from './metaclasses.js';
__nest__ (metaclasses, '', __module_metaclasses__);
import * as __module_local_classes__ from './local_classes.js';
__nest__ (local_classes, '', __module_local_classes__);
import * as __module_list_comprehensions__ from './list_comprehensions.js';
__nest__ (list_comprehensions, '', __module_list_comprehensions__);
import * as __module_lambda_functions__ from './lambda_functions.js';
__nest__ (lambda_functions, '', __module_lambda_functions__);
import * as __module_iterators_and_generators__ from './iterators_and_generators.js';
__nest__ (iterators_and_generators, '', __module_iterators_and_generators__);
import * as __module_indices_and_slices__ from './indices_and_slices.js';
__nest__ (indices_and_slices, '', __module_indices_and_slices__);
import * as __module_globals_function__ from './globals_function.js';
__nest__ (globals_function, '', __module_globals_function__);
import * as __module_general_functions__ from './general_functions.js';
__nest__ (general_functions, '', __module_general_functions__);
import * as __module_fstrings__ from './fstrings.js';
__nest__ (fstrings, '', __module_fstrings__);
import * as __module_extended_slices__ from './extended_slices.js';
__nest__ (extended_slices, '', __module_extended_slices__);
import * as __module_executable_comments__ from './executable_comments.js';
__nest__ (executable_comments, '', __module_executable_comments__);
import * as __module_exceptions__ from './exceptions.js';
__nest__ (exceptions, '', __module_exceptions__);
import * as __module_docstrings__ from './docstrings.js';
__nest__ (docstrings, '', __module_docstrings__);
import * as __module_div_pulls__ from './div_pulls.js';
__nest__ (div_pulls, '', __module_div_pulls__);
import * as __module_div_issues__ from './div_issues.js';
__nest__ (div_issues, '', __module_div_issues__);
import * as __module_dictionaries__ from './dictionaries.js';
__nest__ (dictionaries, '', __module_dictionaries__);
import * as __module_dict_comprehensions__ from './dict_comprehensions.js';
__nest__ (dict_comprehensions, '', __module_dict_comprehensions__);
import * as __module_decorators__ from './decorators.js';
__nest__ (decorators, '', __module_decorators__);
import * as __module_data_structures__ from './data_structures.js';
__nest__ (data_structures, '', __module_data_structures__);
import * as __module_data_classes__ from './data_classes.js';
__nest__ (data_classes, '', __module_data_classes__);
import * as __module_dashed_numbers__ from './dashed_numbers.js';
__nest__ (dashed_numbers, '', __module_dashed_numbers__);
import * as __module_control_structures__ from './control_structures.js';
__nest__ (control_structures, '', __module_control_structures__);
import * as __module_conditional_expressions__ from './conditional_expressions.js';
__nest__ (conditional_expressions, '', __module_conditional_expressions__);
import * as __module_complex_numbers__ from './complex_numbers.js';
__nest__ (complex_numbers, '', __module_complex_numbers__);
import * as __module_classes__ from './classes.js';
__nest__ (classes, '', __module_classes__);
import * as __module_callable_test__ from './callable_test.js';
__nest__ (callable_test, '', __module_callable_test__);
import * as __module_byte_arrays__ from './byte_arrays.js';
__nest__ (byte_arrays, '', __module_byte_arrays__);
import * as __module_builtin_super__ from './builtin_super.js';
__nest__ (builtin_super, '', __module_builtin_super__);
import * as __module_attribs_by_name__ from './attribs_by_name.js';
__nest__ (attribs_by_name, '', __module_attribs_by_name__);
import * as __module_py_arguments__ from './arguments.js';
__nest__ (py_arguments, '', __module_py_arguments__);
import * as __module_org_transcrypt_autotester__ from './org.transcrypt.autotester.js';
__nest__ (org, 'transcrypt.autotester', __module_org_transcrypt_autotester__);
var __all__ = dict ({get __name__ () {return __name__;}, set __name__ (value) {__name__ = value;}, get autoTester () {return autoTester;}, set autoTester (value) {autoTester = value;}});
var __name__ = '__main__';
export var autoTester = org.transcrypt.autotester.AutoTester ();
autoTester.run (py_arguments, 'arguments');
autoTester.run (attribs_by_name, 'attribs_by_name');
autoTester.run (builtin_super, 'builtin_super');
autoTester.run (byte_arrays, 'byte_arrays');
autoTester.run (callable_test, 'callable');
autoTester.run (classes, 'classes');
autoTester.run (complex_numbers, 'complex_numbers');
autoTester.run (conditional_expressions, 'conditional_expressions');
autoTester.run (control_structures, 'control_structures');
autoTester.run (dashed_numbers, 'dashed_numbers');
autoTester.run (data_classes, 'data_classes');
autoTester.run (data_structures, 'data_structures');
autoTester.run (decorators, 'decorators');
autoTester.run (dict_comprehensions, 'dict_comprehensions');
autoTester.run (dictionaries, 'dictionaries');
autoTester.run (div_issues, 'div_issues');
autoTester.run (div_pulls, 'div_pulls');
autoTester.run (docstrings, 'docstrings');
autoTester.run (exceptions, 'exceptions');
autoTester.run (executable_comments, 'executable_comments');
autoTester.run (extended_slices, 'extended_slices');
autoTester.run (fstrings, 'fstrings');
autoTester.run (general_functions, 'general_functions');
autoTester.run (globals_function, 'globals_function');
autoTester.run (indices_and_slices, 'indices_and_slices');
autoTester.run (iterators_and_generators, 'iterators_and_generators');
autoTester.run (lambda_functions, 'lambda_functions');
autoTester.run (list_comprehensions, 'list_comprehensions');
autoTester.run (local_classes, 'local_classes');
autoTester.run (metaclasses, 'metaclasses');
autoTester.run (method_and_class_decorators, 'method_and_class_decorators');
autoTester.run (module_builtin, 'module_builtin');
autoTester.run (module_cmath, 'module_cmath');
autoTester.run (module_datetime, 'module_datetime');
autoTester.run (module_itertools, 'module_itertools');
autoTester.run (module_math, 'module_math');
autoTester.run (module_unicodedata, 'module_unicodedata');
autoTester.run (modules, 'modules');
autoTester.run (nonlocals, 'nonlocals');
autoTester.run (operator_overloading, 'operator_overloading');
autoTester.run (properties, 'properties');
autoTester.run (reprtest, 'repr_str');
autoTester.run (proxies, 'proxies');
autoTester.run (set_comprehensions, 'set_comprehensions');
autoTester.run (simple_and_augmented_assignment, 'simple_and_augmented_assignment');
autoTester.run (string_format, 'string_format');
autoTester.run (truthyness, 'truthyness');
autoTester.run (tuple_assignment, 'tuple_assignment');
autoTester.done ();

//# sourceMappingURL=autotest.map